# Description:
#   The contents of the configuration data, such as the specified partition path, the total 
#   number of classes in the dataset, and the name of each class.

# The path to the main directory of the dataset.
path: '/content/drive/MyDrive/Synthetic_Data/coco128'

# The absolute path to the specified partition folder (train, validation, test) that contains 
# the dataset images as well as the labels.
train: images/train2017
val: images/train2017
test: images/train2017

# Parameters:
#   The total number of classes in the dataset.
nc: 1 
#   ID name of each class.
names: ['T_Joint']