# Description:
#   The contents of the configuration data, such as the specified partition path, the total 
#   number of classes in the dataset, and the name of each class.

# The path to the main directory of the dataset.
#   Name of the dataset:
#     Dataset_Type_{dataset_type}
#   Note:
#     dataset_type: 
#       The identification number of the dataset type.
path: '/content/drive/MyDrive/YOLOv8_Custom_Dataset/Data/Dataset_Type_0'

# The absolute path to the specified partition folder (train, validation, test) that contains 
# the dataset images as well as the labels.
train: images/train
val: images/valid
test: images/test

# Parameters:
#   The total number of classes in the dataset.
nc: 2 
#   ID name of each class.
names: ['T_Joint', 'Metal_Blank']